"""Canonical JSON Schema for the allocation contracts (allocate.md §5; conventions.md §3).

The Pydantic models are the source of truth; this exports their JSON Schema so an external /
cross-language consumer has a first-class, checked-in schema. The schema files under
``schema/`` are generated by ``scripts/export_schemas.py`` from exactly this function, and
``tests/test_schema.py`` regenerates-and-compares as the drift guard — the same "one schema,
kept in lockstep with the typed model" convention Core and Surrogate follow.

Three documents are exported: the solver-neutral **Allocation IR** (the cross-language wire
type, also serialized as Protobuf), and the **AllocationRequest** / **Allocation**
request-response types (Pydantic + JSON Schema only, the Core control-plane pattern).

**Frames/units on the wire (RFC-0007, RM-P1-ALLOC-08).** A ``Task.location`` is a Core
:class:`~astro_mine.core.messages.model.Volume`. Rather than let Pydantic inline a private
copy of that Core message type — and the ``ReferenceFrame``/``FrameClass`` its RFC-0007
``frame_ref`` pulls in — the exported schema ``$ref``\\s Core's canonical ``messages.schema.json``
across files, **by its absolute ``$id``** (:data:`_CORE_MESSAGE_REFS`; RFC-0009 §1). This keeps the
schema free of a local re-derivation of a Core contract (conventions.md §1 tenet 1) and makes
``Volume.frame_ref`` resolve against Core's shared ``ReferenceFrame`` vocabulary instead of a free
string. Because ``jsonschema`` does not fetch external references, a consumer validating against the
exported schema must resolve that cross-file ``$ref`` (messages → units) through
:func:`astro_mine.core.schema_registry`, which carries every Core schema keyed by its ``$id``
(RFC-0009) — see the registry helper in ``tests/test_schema.py`` (kept out of ``src`` so Core's
schema *validators*, i.e. the ``jsonschema``/``referencing`` deps, stay dev-only for this package).
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from astro_mine.allocate.api.model import Allocation, AllocationRequest
from astro_mine.allocate.model.ir.model import AllocationIR
from astro_mine.core.schemas import core_schema

__all__ = ["SCHEMA_BASE_URL", "json_schemas"]

#: The ``$id`` base for the allocation schemas — mirrors Core's ``schemas.astro-mine.org``
#: namespace and the per-interface ``v0.1`` scheme.
SCHEMA_BASE_URL = "https://schemas.astro-mine.org/allocate/v0.1"

#: Core's canonical ``messages`` schema ``$id`` — the one public name for that document
#: (RFC-0009 §1), read from the installed Core through its public accessor so it tracks the
#: pinned Core rather than a hand-copied string.
_CORE_MESSAGES_ID: str = str(core_schema("astro_mine.core.messages", "messages.schema.json")["$id"])

#: Core message types Allocate references but MUST NOT re-derive locally (conventions.md §1
#: tenet 1; RFC-0007 Design §1a) — mapped to the cross-file ``$ref`` that replaces the inlined
#: ``$def``. ``Volume`` carries the frame vocabulary (its RFC-0007 ``frame_ref`` is a Core
#: :class:`~astro_mine.core.units.ReferenceFrame`), so externalizing it makes ``Volume.frame``
#: resolve against Core's canonical frame type (RM-P1-ALLOC-08).
#:
#: The ``$ref`` names Core's schema by its **absolute** ``$id`` (RFC-0009 §1), never by a relative
#: path. The old form — ``../../core/messages/v0.1/messages.schema.json`` — resolved correctly, but
#: only because Core's ``$id`` *path* happened to be ``/core/messages/v0.1/``: it encoded Core's URI
#: **layout** rather than Core's **name**, a structure Core never promised to keep (the ``$id`` is
#: append-only API; its path shape is not). That is the coupling that broke ``guard`` / ``prospect``
#: / ``studio`` in astro-mine-core#54 — path arithmetic that worked right up until it didn't.
_CORE_MESSAGE_REFS = {
    "Volume": f"{_CORE_MESSAGES_ID}#/$defs/Volume",
}


def _local_ref_names(node: Any, acc: set[str]) -> None:
    """Collect every ``#/$defs/<name>`` target reachable from ``node`` into ``acc``."""
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/$defs/"):
            acc.add(ref[len("#/$defs/") :])
        for value in node.values():
            _local_ref_names(value, acc)
    elif isinstance(node, list):
        for item in node:
            _local_ref_names(item, acc)


def _prune_unused_defs(schema: dict[str, Any]) -> None:
    """Drop ``$defs`` entries no longer reachable from the schema root (in place).

    After a Core type is externalized to a cross-file ``$ref``, the nested ``$defs`` it was
    the sole referrer of (e.g. ``ReferenceFrame``/``FrameClass`` behind ``Volume.frame_ref``)
    become orphans; removing them keeps the exported schema free of a Core-type re-derivation.
    """
    defs: dict[str, Any] = schema.get("$defs", {})
    if not defs:
        return
    root_view = {k: v for k, v in schema.items() if k != "$defs"}
    reachable: set[str] = set()
    _local_ref_names(root_view, reachable)
    frontier = set(reachable)
    while frontier:
        name = frontier.pop()
        target = defs.get(name)
        if target is None:
            continue
        found: set[str] = set()
        _local_ref_names(target, found)
        fresh = found - reachable
        reachable |= fresh
        frontier |= fresh
    for name in [n for n in defs if n not in reachable]:
        del defs[name]


def _externalize_core_types(schema: dict[str, Any]) -> dict[str, Any]:
    """Rewrite inlined Core message ``$def``\\s to cross-file ``$ref``\\s (``_CORE_MESSAGE_REFS``).

    Every ``{"$ref": "#/$defs/<name>"}`` for a mapped type is replaced with its external
    cross-file ``$ref``, the local ``$def`` is dropped, and any now-orphaned nested ``$defs``
    are pruned — so the schema references Core's canonical contract instead of copying it.
    """

    def rewrite(node: Any) -> Any:
        if isinstance(node, dict):
            ref = node.get("$ref")
            if isinstance(ref, str) and ref.startswith("#/$defs/"):
                external = _CORE_MESSAGE_REFS.get(ref[len("#/$defs/") :])
                if external is not None:
                    return {"$ref": external}
            return {key: rewrite(value) for key, value in node.items()}
        if isinstance(node, list):
            return [rewrite(item) for item in node]
        return node

    rewritten: dict[str, Any] = rewrite(schema)
    defs = rewritten.get("$defs")
    if isinstance(defs, dict):
        for name in _CORE_MESSAGE_REFS:
            defs.pop(name, None)
        _prune_unused_defs(rewritten)
    return rewritten


def _with_meta(model: type[BaseModel], slug: str) -> dict[str, Any]:
    schema = _externalize_core_types(model.model_json_schema())
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{SCHEMA_BASE_URL}/{slug}.schema.json",
        **schema,
    }


def json_schemas() -> dict[str, dict[str, Any]]:
    """Map each canonical schema filename to its JSON Schema document.

    The single definition both ``scripts/export_schemas.py`` (which writes the files) and
    the drift-guard test consume, so the checked-in files can never silently diverge from
    the models.
    """
    return {
        "allocation_ir.schema.json": _with_meta(AllocationIR, "allocation-ir"),
        "allocation_request.schema.json": _with_meta(AllocationRequest, "allocation-request"),
        "allocation.schema.json": _with_meta(Allocation, "allocation"),
    }
