"""Allocate's scaffold for the umbrella CLI — `astro-mine plugin new solver`.

RFC-0011 §7 puts the scaffolding *verb* in the umbrella, because scaffolding spans components and
has no single-component home. It leaves the *template* with whoever hosts the extension group, and
``astro_mine.allocate.solvers`` is Allocate's.

**This is the one extension point that is safe to open precisely because Allocate is not the safety
authority** (`allocate.md §9`). Every feasible plan, from any backend, is independently re-checked
against the IR before it is used — which is exactly what makes accepting a third-party solver
reasonable rather than reckless, and it is worth an author knowing up front: a solver that yields a
plausible-but-wrong plan is caught, not trusted.

Three things the template has to get right:

1. **The entry-point name is the backend id**, recorded in a plan's ``provenance.backend``. Which
   solver produced a plan is a fact a reader has to be able to recover.
2. **A built-in id may not be shadowed.** Advertising ``cp-sat`` is a hard error naming both
   claimants, for the same provenance reason. The scaffold refuses up front rather than emitting a
   package that fails at the first resolve.
3. **Incumbents stream with monotonically improving bounds**, the last carrying the terminal status.
   A solver that yields one final answer works but gives up the anytime behaviour the IR was
   designed for, so the template delegates to the shipped stub — which already streams correctly —
   rather than showing a single ``yield``.

**Nothing here imports the umbrella.** The contract is structural — ``name``, ``help``,
``add_arguments(parser)``, ``run(args) -> int``. ``astro-mine-cli`` is not a dependency of this
package and must not become one.
"""

from __future__ import annotations

import argparse
import keyword
import re
import sys
from pathlib import Path

__all__ = ["solver_scaffold"]

_USAGE_ERROR = 2


def _pyproject(*, distribution: str, module: str, backend: str) -> str:
    return f"""\
# Generated by `astro-mine plugin new solver`.
#
# Install this package and `{backend}` is selectable as an AllocationPlanner backend. Nothing has to
# be registered anywhere else, and no Astro-Mine repo has to change.
#
# The entry-point NAME is the backend id, recorded in a plan's `provenance.backend`. Which solver
# produced a plan is provenance, so it may not shadow a built-in.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{distribution}"
version = "0.1.0"
description = "An allocation solver backend contributed to Astro-Mine-Allocate."
requires-python = ">=3.12"
# Add your own solver dependency here (OR-Tools, a MIP library, your own engine). Note what is NOT
# here: astro-mine-cli. The umbrella loads this package; it is not a dependency of it.
dependencies = ["astro-mine-allocate"]

[project.entry-points."astro_mine.allocate.solvers"]
{backend} = "{module}:{_symbol(backend)}"

[tool.hatch.build.targets.wheel]
packages = ["src/{module}"]
"""


def _module(*, backend: str) -> str:
    symbol = _symbol(backend)
    return f'''\
"""An allocation solver backend — `{backend}`.

Generated by `astro-mine plugin new solver`.

**The contract** is ``solve(ir, budget, *, hints=None) -> Iterator[Incumbent]``: lower the
solver-neutral Allocation IR to your encoding, search within the budget, and **yield incumbents with
monotonically improving bounds**, the last carrying the terminal status. Streaming is the point —
yielding one final answer works and throws away the anytime behaviour the IR was designed for.

**Your plan is re-checked.** Every feasible plan, from any backend, is independently verified
against the IR before it is used: Allocate is not the safety authority. That is what makes an open
solver seam reasonable — a plausible-but-wrong plan is caught rather than trusted — and it means you
can develop a solver without fearing that a bug becomes a safety event.

**Your id is provenance.** It is recorded in `provenance.backend`, so a reader can always recover
which solver produced a plan. That is why it may not shadow a built-in.
"""

from __future__ import annotations

from collections.abc import Iterator, Mapping
from typing import Any

from astro_mine.allocate.solvers.trivial import TrivialStubSolver


class {symbol.title().replace("_", "")}:
    """Delegates to the shipped stub, so it produces valid streaming plans from the first commit.

    Replace `solve` with your own encoding. Starting from the stub means the plumbing — the
    registry, provenance, the independent re-check — is proven before you introduce a search that
    can fail for a reason of its own.
    """

    def __init__(self, *, task_kinds: Mapping[str, Any], durations: Any | None = None) -> None:
        # The plan-decode context the registry passes every backend: what each task is, and how
        # long each (agent, task) pairing takes.
        self._inner = TrivialStubSolver(task_kinds=task_kinds, durations=durations)

    def solve(
        self, ir: Any, budget: Any, *, hints: Mapping[str, float] | None = None
    ) -> Iterator[Any]:
        """Yield incumbents with improving bounds; the last carries the terminal status."""
        yield from self._inner.solve(ir, budget, hints=hints)


#: The object the entry point resolves to — a factory, so the registry builds one per solve.
{symbol} = {symbol.title().replace("_", "")}
'''


class _SolverScaffold:
    """`astro-mine plugin new solver <dir>` — a package registering an allocation backend."""

    name = "solver"
    help = "an allocation backend (astro_mine.allocate.solvers)"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.description = (
            "Scaffold a package that contributes a solver backend to Allocate. The entry-point "
            "name is the backend id, recorded in a plan's provenance; it cannot shadow a built-in."
        )
        parser.add_argument(
            "--backend",
            default="demo-solver",
            help="the backend id, as selected and recorded in provenance (default: demo-solver)",
        )
        parser.add_argument("--distribution", help="distribution name (default: directory name)")
        parser.add_argument("--module", help="import package (default: distribution, `-` as `_`)")

    def run(self, args: argparse.Namespace) -> int:
        from astro_mine.allocate.solvers.registry import _LOADERS

        target = Path(args.output)
        distribution = args.distribution or target.name
        module = args.module or re.sub(r"[-.]", "_", distribution)
        backend = args.backend

        if backend in _LOADERS:
            print(
                f"astro-mine plugin new solver: {backend!r} is a built-in backend id and cannot be "
                f"shadowed — advertising it is a hard error naming both claimants, because which "
                f"solver produced a plan is provenance. Pick your own id with --backend.",
                file=sys.stderr,
            )
            return _USAGE_ERROR
        if not module.isidentifier() or keyword.iskeyword(module):
            print(
                f"astro-mine plugin new solver: {module!r} is not a usable Python package name; "
                f"pass --module explicitly",
                file=sys.stderr,
            )
            return _USAGE_ERROR

        files = {
            target / "pyproject.toml": _pyproject(
                distribution=distribution, module=module, backend=backend
            ),
            target / "src" / module / "__init__.py": _module(backend=backend),
        }
        existing = [path for path in files if path.exists()]
        if existing and not args.force:
            listing = ", ".join(str(path) for path in existing)
            print(f"{listing}: file exists (use --force to overwrite)", file=sys.stderr)
            return 1
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
        print(
            f"\nInstall it and the id becomes selectable:\n  pip install -e {target}\n"
            f"  # then: AllocationPlanner(backend={backend!r})"
        )
        return 0


def _symbol(name: str) -> str:
    """A backend id may carry a hyphen; a Python symbol may not."""
    return re.sub(r"[-.]", "_", name)


solver_scaffold = _SolverScaffold()
