"""Sim's scaffold for the umbrella CLI — `astro-mine plugin new provider`.

RFC-0011 §7 puts the scaffolding *verb* in the umbrella, because scaffolding spans components and
has no single-component home. It leaves the *template* with whoever hosts the extension group, and
``astro_mine.providers`` is Sim's (``sim/runtime/content.py``).

**This group is the rebuild-from-a-pulled-bundle seam**, and it has two properties an author has to
get right on the first try, because both fail in ways that do not point at their cause:

1. **The entry-point name is a Core ``PluginKind`` value**, not a free-form label. It is the one
   group in the platform whose names come from Core's closed vocabulary — a factory registered
   under an invented name is discovered and then never matched to any pin, so content silently
   resolves to no provider. The scaffold takes the kind as a choice from that vocabulary and refuses
   anything else.
2. **The factory must import only Core and its own package — never ``astro_mine.sim``.** That
   one-way dependency is the whole point of the seam: Sim reconstructs a live provider from pulled
   bytes *without importing the producer*, so the producer must not import Sim back
   (``conventions.md §1.1``). A template that imported Sim for a convenience type would teach every
   producer to close the cycle, and a test pins that it does not.

**Nothing here imports the umbrella.** The contract is structural — ``name``, ``help``,
``add_arguments(parser)``, ``run(args) -> int`` — the same four members a verb has.
``astro-mine-cli`` is not a dependency of this package and must not become one.
"""

from __future__ import annotations

import argparse
import keyword
import re
import sys
from pathlib import Path

__all__ = ["provider_scaffold"]

_USAGE_ERROR = 2

#: The Core ``PluginKind`` values that name a *reconstructable content provider*. Not the whole
#: enum: `asset`, `design` and `campaign` are packaging metadata nobody loads as code, and the Sim
#: extension points (`regime_engine`, `sensor_model`, `coupling_scheme`) are resolved through a
#: different surface. These are the kinds a pulled bundle rebuilds into a live provider.
PROVIDER_KINDS = (
    "world_provider",
    "body_pack",
    "field_model",
    "resource_field_backend",
    "observation_model",
    "prior_recipe",
    "info_gain_objective",
    "comms_model",
)


def _pyproject(*, distribution: str, module: str, kind: str) -> str:
    return f"""\
# Generated by `astro-mine plugin new provider`.
#
# Install this package and Sim reconstructs your provider from a pulled bundle. Nothing has to be
# registered anywhere else, and no Astro-Mine repo has to change.
#
# The entry-point NAME is a Core PluginKind value -- `{kind}` -- not a label you choose. Sim keys
# the factory by that value and matches it against a scenario's content pins; an invented name is
# discovered and then never matched, so content resolves to no provider without an error.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{distribution}"
version = "0.1.0"
description = "A content provider contributed to the Astro-Mine platform."
requires-python = ">=3.12"
# Core only. NOT astro-mine-sim: Sim reconstructs your provider without importing you, and this
# package must not import Sim back. NOT astro-mine-cli either -- the umbrella loads this; it is
# not a dependency of it.
dependencies = ["astro-mine-core"]

[project.entry-points."astro_mine.providers"]
{kind} = "{module}:from_bundle"

[tool.hatch.build.targets.wheel]
packages = ["src/{module}"]
"""


def _module(*, kind: str) -> str:
    return f'''\
"""A content provider rebuilt from a pulled bundle ({kind}).

Generated by `astro-mine plugin new provider`.

**The contract** is ``(manifest, layers) -> provider``: a Core ``PluginManifest`` and a mapping from
an OCI layer's media type to its raw bytes, in; a live Core provider out. Sim resolves a scenario's
content by digest, pulls the bytes, and calls this — so the provider is reconstructed on a machine
that may have never seen the producer that published it.

**Import only Core and your own package here.** Never ``astro_mine.sim``. Sim discovers this factory
through installed metadata and never imports the producer; importing Sim back would close the cycle
the seam exists to prevent (``conventions.md §1.1``). If you need a type from Sim, you have found a
gap in Core, not a reason to import Sim.

Keep this module cheap to import: it is loaded when content is resolved, which happens per scenario.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any


class DemoProvider:
    """A live Core provider, rebuilt from bundle layers.

    Replace this with the real thing — parse the layers your producer published and answer the Core
    interface for `{kind}`. What matters structurally is that construction happens *here*, from
    bytes, with no call back to whoever produced them.
    """

    def __init__(self, manifest: Any, layers: Mapping[str, bytes]) -> None:
        self.manifest = manifest
        self.layers = dict(layers)


def from_bundle(manifest: Any, layers: Mapping[str, bytes]) -> DemoProvider:
    """The factory Sim calls: ``(PluginManifest, {{media_type: bytes}}) -> provider``."""
    return DemoProvider(manifest, layers)
'''


class _ProviderScaffold:
    """`astro-mine plugin new provider <dir>` — a package registering a content provider."""

    name = "provider"
    help = "a content provider (astro_mine.providers)"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.description = (
            "Scaffold a package that rebuilds a content provider from a pulled bundle. The "
            "entry-point name is a Core PluginKind value, not a label — pick it with --kind."
        )
        parser.add_argument(
            "--kind",
            default="world_provider",
            choices=PROVIDER_KINDS,
            help="the Core PluginKind this provider answers (default: world_provider)",
        )
        parser.add_argument("--distribution", help="distribution name (default: directory name)")
        parser.add_argument("--module", help="import package (default: distribution, `-` as `_`)")

    def run(self, args: argparse.Namespace) -> int:
        target = Path(args.output)
        distribution = args.distribution or target.name
        module = args.module or re.sub(r"[-.]", "_", distribution)
        if not module.isidentifier() or keyword.iskeyword(module):
            print(
                f"astro-mine plugin new provider: {module!r} is not a usable Python package name; "
                f"pass --module explicitly",
                file=sys.stderr,
            )
            return _USAGE_ERROR

        files = {
            target / "pyproject.toml": _pyproject(
                distribution=distribution, module=module, kind=args.kind
            ),
            target / "src" / module / "__init__.py": _module(kind=args.kind),
        }
        existing = [path for path in files if path.exists()]
        if existing and not args.force:
            listing = ", ".join(str(path) for path in existing)
            print(f"{listing}: file exists (use --force to overwrite)", file=sys.stderr)
            return 1
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
        print(f"\nInstall it and Sim rebuilds your content from a pin:\n  pip install -e {target}")
        return 0


provider_scaffold = _ProviderScaffold()
