# syntax=docker/dockerfile:1
#
# Reproducible workload image -- generated by
# astro_mine.cloud.packaging.render_dockerfile (RM-P0-CLOUD-01). A digest-pinned base, a
# fixed SOURCE_DATE_EPOCH, and no build-time network make the build byte-stable, so a
# laptop image and a cluster image are identical (cloud.md §4, §7; conventions.md §7).
# Do not hand-edit -- regenerate it from the BuildSpec.
#
FROM docker.io/library/python@sha256:cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe

# Deterministic build clock -- reproducible timestamps in the image metadata.
ARG SOURCE_DATE_EPOCH=0
ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}

# OCI image annotations (sorted for a stable layer).
LABEL org.opencontainers.image.base.digest="sha256:cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe" \
      org.opencontainers.image.base.name="docker.io/library/python" \
      org.opencontainers.image.revision="cafecafecafecafecafecafecafecafecafecafe" \
      org.opencontainers.image.source="https://github.com/astro-mine/astro-mine-platform" \
      org.opencontainers.image.title="ghcr.io/astro-mine/astro-mine-sim" \
      org.opencontainers.image.version="0.1.0"

# Unprivileged by default: a numeric uid:gid so no package manager / distro is assumed
# (distroless-compatible). Cloud never runs workloads as root in shared tenancy
# (cloud.md §9).
USER 65532:65532
WORKDIR /work

ENTRYPOINT ["python", "-m", "astro_mine.sim"]
