# SPDX-License-Identifier: Apache-2.0
"""The Allocation IR — solver-neutral model, compiler, verifier, and wire form.

The stable internal contract that lets solver backends be true plugins (allocate.md §3, §5):
:mod:`.model` (the ``AllocationIR`` decision-variable / constraint / objective-term types),
:mod:`.compile` (``compile_request``: ``AllocationRequest`` → IR), :mod:`.verify`
(``verify_feasible``: the independent, Guard-recheckable feasibility oracle), and :mod:`.wire`
(the byte-stable Protobuf round-trip). The generated Protobuf bindings live under
``_proto/`` (regenerated by ``scripts/gen_proto.sh``).
"""

from __future__ import annotations
