"""Learn's scaffolds for the umbrella CLI — `astro-mine plugin new algorithm | curriculum`.

RFC-0011 §7 puts the scaffolding *verbs* in the umbrella, because scaffolding spans components and
has no single-component home. It leaves the *templates* with whoever hosts the extension group, and
``astro_mine.learn.algorithms`` and ``astro_mine.learn.curricula`` are Learn's.

**Both of Learn's groups name a plugin by something other than its entry-point name, and that is
the single thing these scaffolds exist to get right.** It is the platform's sharpest plugin trap,
because getting it wrong is *silent*: the package installs, the registry loads it, and it appears
under a name the author did not choose — so the id they put in their `TrainConfig` resolves to
nothing, and the error arrives nowhere near the cause.

* An **algorithm** is keyed by ``spec.capability_tag``, read off the loaded object. The entry-point
  name is ignored outright.
* A **curriculum** is keyed by which of two things the callable returns: a ``CurriculumSpec``
  registers under its own ``spec.name`` and the entry-point name is ignored; a factory registers
  under the entry-point name.

So both templates set the authoritative name in *one* place and repeat it in the entry point, and
the tests assert the plugin registers under the name the author asked for — not merely that it
registers.

**Nothing here imports the umbrella.** The contract is structural — ``name``, ``help``,
``add_arguments(parser)``, ``run(args) -> int`` — the same four members a verb has (``conventions.md
§1.1``). ``astro-mine-cli`` is not a dependency of this package and must not become one.
"""

from __future__ import annotations

import argparse
import keyword
import re
import sys
from pathlib import Path

__all__ = ["algorithm_scaffold", "curriculum_scaffold"]

_USAGE_ERROR = 2


# --------------------------------------------------------------------------- algorithm


def _algorithm_pyproject(*, distribution: str, module: str, entry: str) -> str:
    return f"""\
# Generated by `astro-mine plugin new algorithm`.
#
# Install this package and Learn's AlgorithmRegistry finds it. Nothing has to be registered
# anywhere else, and no Astro-Mine repo has to change.
#
# NOTE the entry-point name below is a label only. The registry keys your algorithm by
# `spec.capability_tag`, read off the loaded object — see the module for the name that counts.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{distribution}"
version = "0.1.0"
description = "A MARL algorithm contributed to Astro-Mine-Learn."
requires-python = ">=3.12"
# Note what is NOT here: astro-mine-cli. The umbrella loads this package; it is not a dependency
# of it.
dependencies = ["astro-mine-learn"]

[project.entry-points."astro_mine.learn.algorithms"]
{entry} = "{module}:build"

[tool.hatch.build.targets.wheel]
packages = ["src/{module}"]
"""


def _algorithm_module(*, tag: str, paradigm: str) -> str:
    return f'''\
"""A MARL algorithm for Astro-Mine-Learn.

Generated by `astro-mine plugin new algorithm`.

**The name that matters is the capability tag, not the entry-point name.** Learn's registry keys
this algorithm by ``spec.capability_tag`` — read off the loaded object — and ignores what the entry
point is called. Change the tag below and the id you select in a ``TrainConfig`` changes with it;
change the entry-point name and nothing changes at all.

    astro-mine-learn train --algorithm {tag} ...

The contract is a zero-argument callable returning an ``Algorithm``: a ``spec`` property and a
``make_trainer(env, config, ...)`` that builds a ``Trainer``. This one subclasses a shipped baseline
so it runs from the first commit — replace the internals, keep the tag.
"""

from __future__ import annotations

from astro_mine.learn.algos._contract import AlgorithmSpec
from astro_mine.learn.algos.ippo import IppoAlgorithm

#: The registry's key for this algorithm. Set it deliberately: it is the id a user selects, and it
#: must not collide with a shipped baseline (`marl.independent.ppo`, `marl.centralized.ppo`,
#: `marl.value_decomposition.qmix`, ...).
SPEC = AlgorithmSpec(
    name="{tag.rsplit(".", 1)[-1]}",
    capability_tag="{tag}",
    # `ctde` builds a centralized critic per env and exposes it on the trainer; `decentralized`
    # does not. Declare what your algorithm actually does — the trainer is built from this.
    paradigm="{paradigm}",
    description="A MARL algorithm contributed as a Learn plugin.",
)


class DemoAlgorithm(IppoAlgorithm):
    """Starts as a shipped baseline with its own identity, so it trains before you change it.

    Subclassing is convenience, not contract: the registry checks shape. Replace `make_trainer`
    with your own once the plumbing is proven.
    """

    @property
    def spec(self) -> AlgorithmSpec:
        return SPEC


def build() -> DemoAlgorithm:
    """The entry-point provider: zero arguments in, an Algorithm out."""
    return DemoAlgorithm()
'''


class _AlgorithmScaffold:
    """`astro-mine plugin new algorithm <dir>` — a package registering a MARL algorithm."""

    name = "algorithm"
    help = "a MARL algorithm (astro_mine.learn.algorithms)"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.description = (
            "Scaffold a package that contributes a MARL algorithm to Learn. The registry keys it "
            "by its capability tag, not its entry-point name — the template sets both from --tag."
        )
        parser.add_argument(
            "--tag",
            default="marl.demo.algorithm",
            help="capability tag — the id the registry uses (default: marl.demo.algorithm)",
        )
        parser.add_argument(
            "--paradigm",
            default="decentralized",
            choices=("decentralized", "ctde"),
            help="CTDE contract this algorithm honours (default: decentralized)",
        )
        parser.add_argument("--distribution", help="distribution name (default: directory name)")
        parser.add_argument("--module", help="import package (default: distribution, `-` as `_`)")

    def run(self, args: argparse.Namespace) -> int:
        target = Path(args.output)
        distribution = args.distribution or target.name
        module = args.module or re.sub(r"[-.]", "_", distribution)
        if (bad := _bad_module(module)) is not None:
            print(bad, file=sys.stderr)
            return _USAGE_ERROR

        files = {
            target / "pyproject.toml": _algorithm_pyproject(
                distribution=distribution, module=module, entry=_symbol(args.tag)
            ),
            target / "src" / module / "__init__.py": _algorithm_module(
                tag=args.tag, paradigm=args.paradigm
            ),
        }
        status = _write(files, force=args.force)
        if status == 0:
            print(
                f"\nInstall it and Learn finds it:\n  pip install -e {target}\n  # then select it:"
                f"\n  astro-mine-learn train --algorithm {args.tag} ..."
            )
        return status


# --------------------------------------------------------------------------- curriculum


def _curriculum_pyproject(*, distribution: str, module: str, entry: str) -> str:
    return f"""\
# Generated by `astro-mine plugin new curriculum`.
#
# NOTE how this plugin is *named* depends on what the callable returns. This template returns a
# CurriculumSpec, which registers under its own `spec.name` — the entry-point name below is
# ignored. (A factory would register under the entry-point name instead.) Both are kept equal here
# so the distinction cannot bite you; see the module.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{distribution}"
version = "0.1.0"
description = "A training curriculum contributed to Astro-Mine-Learn."
requires-python = ">=3.12"
# Note what is NOT here: astro-mine-cli. The umbrella loads this package; it is not a dependency
# of it.
dependencies = ["astro-mine-learn"]

[project.entry-points."astro_mine.learn.curricula"]
{entry} = "{module}:build"

[tool.hatch.build.targets.wheel]
packages = ["src/{module}"]
"""


def _curriculum_module(*, curriculum: str) -> str:
    return f'''\
"""A staged training curriculum for Astro-Mine-Learn.

Generated by `astro-mine plugin new curriculum`.

**How this plugin is named depends on what `build` returns**, which is the trap worth knowing
before you edit it:

* returning a ``CurriculumSpec`` — as below — registers it under **``spec.name``**, and the
  entry-point name is ignored;
* returning a ``CurriculumFactory`` (``(seed, base_config) -> Curriculum``, for an automatic
  curriculum) registers it under the **entry-point name** instead.

Both are set to ``{curriculum}`` here, so the distinction cannot bite you until you mean it.

A ladder is a sequence of stages, each a comms regime plus training-config overrides plus the rule
that promotes out of it. Stages advance on sustained progress — ``patience`` iterations above the
bar — so a ladder never advances on one lucky iteration.
"""

from __future__ import annotations

from astro_mine.learn.curriculum.spec import AdvanceRule, CurriculumSpec, StageSpec
from astro_mine.learn.envs import CommsModelConfig, DropConfig


def build() -> CurriculumSpec:
    """The entry-point provider: zero arguments in, a CurriculumSpec out."""
    return CurriculumSpec(
        # THE registry key. Renaming this renames the curriculum; renaming the entry point does not.
        name="{curriculum}",
        stages=(
            StageSpec(
                name="clear",
                # An identity channel: every message is delivered. Learn the task itself first.
                comms=CommsModelConfig(),
                advance=AdvanceRule(metric="mean_reward", threshold=-0.05, patience=2),
            ),
            StageSpec(
                name="degraded",
                # The same task under intermittent information — the charter §8 regime, where a
                # swarm must degrade gracefully rather than collapse.
                comms=CommsModelConfig(drop=DropConfig(probability=0.3)),
                advance=AdvanceRule(metric="mean_reward", threshold=-0.10, patience=2),
            ),
        ),
    )
'''


class _CurriculumScaffold:
    """`astro-mine plugin new curriculum <dir>` — a package registering a training curriculum."""

    name = "curriculum"
    help = "a training curriculum (astro_mine.learn.curricula)"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.description = (
            "Scaffold a package that contributes a staged curriculum to Learn. A spec-returning "
            "curriculum registers under its own name, not the entry point's — the template sets "
            "both from --name-it."
        )
        parser.add_argument(
            "--name-it",
            dest="curriculum",
            default="demo_ladder",
            help="the curriculum name the registry uses (default: demo_ladder)",
        )
        parser.add_argument("--distribution", help="distribution name (default: directory name)")
        parser.add_argument("--module", help="import package (default: distribution, `-` as `_`)")

    def run(self, args: argparse.Namespace) -> int:
        target = Path(args.output)
        distribution = args.distribution or target.name
        module = args.module or re.sub(r"[-.]", "_", distribution)
        if (bad := _bad_module(module)) is not None:
            print(bad, file=sys.stderr)
            return _USAGE_ERROR

        files = {
            target / "pyproject.toml": _curriculum_pyproject(
                distribution=distribution, module=module, entry=_symbol(args.curriculum)
            ),
            target / "src" / module / "__init__.py": _curriculum_module(curriculum=args.curriculum),
        }
        status = _write(files, force=args.force)
        if status == 0:
            print(
                f"\nInstall it and Learn finds it:\n  pip install -e {target}\n  # then select it:"
                f"\n  astro-mine-learn train --curriculum {args.curriculum} ..."
            )
        return status


# --------------------------------------------------------------------------- shared


def _symbol(name: str) -> str:
    """An entry-point name is free-form; a dotted tag is not a usable one."""
    return re.sub(r"[-.]", "_", name)


def _bad_module(module: str) -> str | None:
    if module.isidentifier() and not keyword.iskeyword(module):
        return None
    return (
        f"astro-mine plugin new: {module!r} is not a usable Python package name; "
        f"pass --module explicitly"
    )


def _write(files: dict[Path, str], *, force: bool) -> int:
    """Write every file, or none of them — a half-written package is worse than none.

    ``--force`` is declared by the umbrella for every kind, so honouring it is not optional: a
    scaffold that ignored it would silently destroy whatever the user had already authored there.
    """
    existing = [path for path in files if path.exists()]
    if existing and not force:
        listing = ", ".join(str(path) for path in existing)
        print(f"{listing}: file exists (use --force to overwrite)", file=sys.stderr)
        return 1
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    return 0


algorithm_scaffold = _AlgorithmScaffold()
curriculum_scaffold = _CurriculumScaffold()
