# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from astro_mine.prospect.service._proto import field_service_pb2 as astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2


class FieldServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetField = channel.unary_unary(
                '/astro_mine.prospect.service.v1.FieldService/GetField',
                request_serializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.FieldRequest.SerializeToString,
                response_deserializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.FieldSnapshot.FromString,
                _registered_method=True)
        self.SubmitObservations = channel.unary_unary(
                '/astro_mine.prospect.service.v1.FieldService/SubmitObservations',
                request_serializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.ObservationBatch.SerializeToString,
                response_deserializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.UpdateAck.FromString,
                _registered_method=True)
        self.StreamBeliefUpdates = channel.unary_stream(
                '/astro_mine.prospect.service.v1.FieldService/StreamBeliefUpdates',
                request_serializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.BeliefUpdate.FromString,
                _registered_method=True)


class FieldServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetField(self, request, context):
        """Fetch the current replayable state of a shared field.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitObservations(self, request, context):
        """Append observations to a field's ordered log; the server re-conditions the one posterior.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBeliefUpdates(self, request, context):
        """Stream belief updates (catch-up + live) so a distributed sim tracks the one posterior.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FieldServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetField': grpc.unary_unary_rpc_method_handler(
                    servicer.GetField,
                    request_deserializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.FieldRequest.FromString,
                    response_serializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.FieldSnapshot.SerializeToString,
            ),
            'SubmitObservations': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitObservations,
                    request_deserializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.ObservationBatch.FromString,
                    response_serializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.UpdateAck.SerializeToString,
            ),
            'StreamBeliefUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBeliefUpdates,
                    request_deserializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.SubscribeRequest.FromString,
                    response_serializer=astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.BeliefUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astro_mine.prospect.service.v1.FieldService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astro_mine.prospect.service.v1.FieldService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FieldService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astro_mine.prospect.service.v1.FieldService/GetField',
            astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.FieldRequest.SerializeToString,
            astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.FieldSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitObservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astro_mine.prospect.service.v1.FieldService/SubmitObservations',
            astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.ObservationBatch.SerializeToString,
            astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.UpdateAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBeliefUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astro_mine.prospect.service.v1.FieldService/StreamBeliefUpdates',
            astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.SubscribeRequest.SerializeToString,
            astro__mine_dot_prospect_dot_service_dot___proto_dot_field__service__pb2.BeliefUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
