# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astro_mine/core/units/_proto/units.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'astro_mine/core/units/_proto/units.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(astro_mine/core/units/_proto/units.proto\x12\x18\x61stro_mine.core.units.v0\"m\n\x0eReferenceFrame\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n\x0b\x66rame_class\x18\x02 \x01(\tR\nframeClass\x12\x1b\n\x06\x63\x65nter\x18\x03 \x01(\tH\x00R\x06\x63\x65nter\x88\x01\x01\x42\t\n\x07_center\"\xd3\x01\n\x0cPlanetaryCRS\x12\x12\n\x04\x62ody\x18\x01 \x01(\tR\x04\x62ody\x12(\n\x10\x62ody_fixed_frame\x18\x02 \x01(\tR\x0e\x62odyFixedFrame\x12,\n\x12reference_radius_m\x18\x03 \x01(\x01R\x10referenceRadiusM\x12#\n\nprojection\x18\x04 \x01(\tH\x00R\nprojection\x88\x01\x01\x12\x19\n\x05\x64\x61tum\x18\x05 \x01(\tH\x01R\x05\x64\x61tum\x88\x01\x01\x42\r\n\x0b_projectionB\x08\n\x06_datum\">\n\x05\x45poch\x12\x1f\n\x0btdb_seconds\x18\x01 \x01(\x01R\ntdbSeconds\x12\x14\n\x05scale\x18\x02 \x01(\tR\x05scale\"w\n\x0b\x45pochWindow\x12\x35\n\x05start\x18\x01 \x01(\x0b\x32\x1f.astro_mine.core.units.v0.EpochR\x05start\x12\x31\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1f.astro_mine.core.units.v0.EpochR\x03\x65ndb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astro_mine.core.units._proto.units_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFERENCEFRAME']._serialized_start=70
  _globals['_REFERENCEFRAME']._serialized_end=179
  _globals['_PLANETARYCRS']._serialized_start=182
  _globals['_PLANETARYCRS']._serialized_end=393
  _globals['_EPOCH']._serialized_start=395
  _globals['_EPOCH']._serialized_end=457
  _globals['_EPOCHWINDOW']._serialized_start=459
  _globals['_EPOCHWINDOW']._serialized_end=578
# @@protoc_insertion_point(module_scope)
