# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from astro_mine.sim.service._proto import environment_pb2 as environment__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in environment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvironmentServiceStub:
    """Sim's Core Environment API, served. The in-process library path is unaffected: this is additive.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/astro_mine.sim.v1.EnvironmentService/Describe',
                request_serializer=environment__pb2.DescribeRequest.SerializeToString,
                response_deserializer=environment__pb2.DescribeResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/astro_mine.sim.v1.EnvironmentService/Reset',
                request_serializer=environment__pb2.ResetRequest.SerializeToString,
                response_deserializer=environment__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_stream(
                '/astro_mine.sim.v1.EnvironmentService/Step',
                request_serializer=environment__pb2.StepRequest.SerializeToString,
                response_deserializer=environment__pb2.StepResponse.FromString,
                _registered_method=True)


class EnvironmentServiceServicer:
    """Sim's Core Environment API, served. The in-process library path is unaffected: this is additive.
    """

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Server-streaming: one response per tick (sim.md §3, §6).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=environment__pb2.DescribeRequest.FromString,
                    response_serializer=environment__pb2.DescribeResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=environment__pb2.ResetRequest.FromString,
                    response_serializer=environment__pb2.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_stream_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=environment__pb2.StepRequest.FromString,
                    response_serializer=environment__pb2.StepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astro_mine.sim.v1.EnvironmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astro_mine.sim.v1.EnvironmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvironmentService:
    """Sim's Core Environment API, served. The in-process library path is unaffected: this is additive.
    """

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astro_mine.sim.v1.EnvironmentService/Describe',
            environment__pb2.DescribeRequest.SerializeToString,
            environment__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astro_mine.sim.v1.EnvironmentService/Reset',
            environment__pb2.ResetRequest.SerializeToString,
            environment__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astro_mine.sim.v1.EnvironmentService/Step',
            environment__pb2.StepRequest.SerializeToString,
            environment__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
