# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: environment.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'environment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65nvironment.proto\x12\x11\x61stro_mine.sim.v1\"\x11\n\x0f\x44\x65scribeRequest\"\xe8\x01\n\x10\x44\x65scribeResponse\x12\x17\n\x0fpossible_agents\x18\x01 \x03(\t\x12P\n\x0f\x63ore_interfaces\x18\x02 \x03(\x0b\x32\x37.astro_mine.sim.v1.DescribeResponse.CoreInterfacesEntry\x12\x12\n\nframe_name\x18\x03 \x01(\t\x12\x10\n\x08scenario\x18\x04 \x01(\t\x12\x0c\n\x04\x64t_s\x18\x05 \x01(\x01\x1a\x35\n\x13\x43oreInterfacesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"*\n\x0cResetRequest\x12\x11\n\x04seed\x18\x01 \x01(\x03H\x00\x88\x01\x01\x42\x07\n\x05_seed\"5\n\rResetResponse\x12\x14\n\x0cobservations\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61gents\x18\x02 \x03(\t\"7\n\x0bStepRequest\x12\x19\n\x11\x61\x63tion_batch_json\x18\x01 \x01(\t\x12\r\n\x05steps\x18\x02 \x01(\x05\"\xdd\x02\n\x0cStepResponse\x12\x14\n\x0cobservations\x18\x01 \x01(\x0c\x12\x0c\n\x04tick\x18\x02 \x01(\x05\x12\x12\n\nsim_time_s\x18\x03 \x01(\x01\x12\x0c\n\x04\x64t_s\x18\x04 \x01(\x01\x12G\n\x0cterminations\x18\x05 \x03(\x0b\x32\x31.astro_mine.sim.v1.StepResponse.TerminationsEntry\x12\x45\n\x0btruncations\x18\x06 \x03(\x0b\x32\x30.astro_mine.sim.v1.StepResponse.TruncationsEntry\x12\x0e\n\x06\x61gents\x18\x07 \x03(\t\x1a\x33\n\x11TerminationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x1a\x32\n\x10TruncationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x32\x80\x02\n\x12\x45nvironmentService\x12S\n\x08\x44\x65scribe\x12\".astro_mine.sim.v1.DescribeRequest\x1a#.astro_mine.sim.v1.DescribeResponse\x12J\n\x05Reset\x12\x1f.astro_mine.sim.v1.ResetRequest\x1a .astro_mine.sim.v1.ResetResponse\x12I\n\x04Step\x12\x1e.astro_mine.sim.v1.StepRequest\x1a\x1f.astro_mine.sim.v1.StepResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'environment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESCRIBERESPONSE_COREINTERFACESENTRY']._loaded_options = None
  _globals['_DESCRIBERESPONSE_COREINTERFACESENTRY']._serialized_options = b'8\001'
  _globals['_STEPRESPONSE_TERMINATIONSENTRY']._loaded_options = None
  _globals['_STEPRESPONSE_TERMINATIONSENTRY']._serialized_options = b'8\001'
  _globals['_STEPRESPONSE_TRUNCATIONSENTRY']._loaded_options = None
  _globals['_STEPRESPONSE_TRUNCATIONSENTRY']._serialized_options = b'8\001'
  _globals['_DESCRIBEREQUEST']._serialized_start=40
  _globals['_DESCRIBEREQUEST']._serialized_end=57
  _globals['_DESCRIBERESPONSE']._serialized_start=60
  _globals['_DESCRIBERESPONSE']._serialized_end=292
  _globals['_DESCRIBERESPONSE_COREINTERFACESENTRY']._serialized_start=239
  _globals['_DESCRIBERESPONSE_COREINTERFACESENTRY']._serialized_end=292
  _globals['_RESETREQUEST']._serialized_start=294
  _globals['_RESETREQUEST']._serialized_end=336
  _globals['_RESETRESPONSE']._serialized_start=338
  _globals['_RESETRESPONSE']._serialized_end=391
  _globals['_STEPREQUEST']._serialized_start=393
  _globals['_STEPREQUEST']._serialized_end=448
  _globals['_STEPRESPONSE']._serialized_start=451
  _globals['_STEPRESPONSE']._serialized_end=800
  _globals['_STEPRESPONSE_TERMINATIONSENTRY']._serialized_start=697
  _globals['_STEPRESPONSE_TERMINATIONSENTRY']._serialized_end=748
  _globals['_STEPRESPONSE_TRUNCATIONSENTRY']._serialized_start=750
  _globals['_STEPRESPONSE_TRUNCATIONSENTRY']._serialized_end=800
  _globals['_ENVIRONMENTSERVICE']._serialized_start=803
  _globals['_ENVIRONMENTSERVICE']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
