"""The one scaffold the umbrella owns: `astro-mine plugin new cli` (RFC-0011 §7).

Every other kind belongs to a component, because the component owns the schema. This one belongs
here for the same reason `validate` does: the group being written against is ``astro_mine.cli``,
and the umbrella owns that group. A scaffold for it would have nowhere else to live.

It is also what keeps this feature from shipping as an empty shell. A dispatcher with no kinds
until eight sibling repos land their halves would repeat the exact problem RFC-0011 §1b fixed for
verbs — and the end-to-end claim the acceptance criteria actually care about (*"a scaffolded
package installs, registers, and is discovered through its entry-point group"*) is provable here,
in this repo's own venv, rather than deferred to a cross-repo test no CI runs.

**Still no dependency.** The emitted files are f-strings over the stdlib. The generated package
declares ``dependencies = []`` and does **not** import ``astro_mine.cli``: the contract is
structural, so a verb plugin depends on the umbrella no more than any component does
(``conventions.md §1.1``). A scaffold that quietly added that import would teach every third-party
author to invert the platform's layering.
"""

from __future__ import annotations

import argparse
import keyword
import re
import sys
from pathlib import Path

__all__ = ["CLI_PLUGIN_SCAFFOLD"]

_USAGE_ERROR = 2

#: PEP 503-ish: what a distribution name may look like on PyPI and in a `pip install` line.
_DISTRIBUTION_RE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$")

#: A verb is typed at a shell prompt, so it is lower-case, and starts with a letter or digit so it
#: can never be mistaken for an option.
_VERB_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def _pyproject(*, distribution: str, module: str, verb: str, description: str) -> str:
    """The packaging half — where the verb is actually registered."""
    return f"""\
# Generated by `astro-mine plugin new cli`.
#
# The entry point below is the whole contract: install this package and `astro-mine {verb}` works.
# Nothing has to be registered anywhere else, and no Astro-Mine repo has to change (RFC-0011 §3).
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{distribution}"
version = "0.1.0"
description = "{description}"
requires-python = ">=3.12"
# The umbrella's contract is structural, so this package does NOT depend on astro-mine-cli.
# Add whatever your verb actually needs -- and nothing it does not, so `astro-mine {verb}` stays
# cheap to install for someone who wants only this one command.
dependencies = []

[project.entry-points."astro_mine.cli"]
{verb} = "{module}:{_symbol(verb)}"

[tool.hatch.build.targets.wheel]
packages = ["src/{module}"]
"""


def _module(*, verb: str, description: str) -> str:
    """The code half — a `Subcommand` by shape, importing nothing from the umbrella."""
    symbol = _symbol(verb)
    return f'''\
"""{description}

Reached as `astro-mine {verb}`, via the ``astro_mine.cli`` entry point in ``pyproject.toml``.

The umbrella dispatches on **shape**, not on a base class: an object with ``name``, ``help``,
``add_arguments`` and ``run`` is a subcommand. That is why nothing here imports
``astro_mine.cli`` -- a plugin must never depend on the thing that loads it.

``add_arguments`` is called only when this verb is the one being run, so the import cost of
whatever you build on is paid by the user who asked for it and by nobody else.
"""

from __future__ import annotations

import argparse


class _{symbol.title().replace("_", "")}:
    #: Must equal the entry-point name in pyproject.toml -- the umbrella routes on that name, and a
    #: mismatch would make this attribute a lie in help output and error messages.
    name = "{verb}"

    #: One line, lower-case, no trailing period: it is rendered in a list.
    help = "describe what this verb does"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        """Declare this verb's own arguments. The parser belongs to the umbrella."""
        parser.add_argument("--name", default="world", help="who to greet")

    def run(self, args: argparse.Namespace) -> int:
        """Do the work. The return value becomes the process exit status."""
        print(f"hello, {{args.name}}")
        return 0


#: The object the entry point resolves to.
{symbol} = _{symbol.title().replace("_", "")}()
'''


class _CliPluginScaffold:
    """`astro-mine plugin new cli <dir>` — a distribution that contributes a verb."""

    name = "cli"
    help = "a package contributing an `astro-mine <verb>` (astro_mine.cli)"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        # `output` and `--force` are already declared by the umbrella (see _new.py): every kind
        # gets the same skeleton, so only what is specific to this one is added here.
        parser.description = (
            "Scaffold an installable package that contributes a verb to the astro-mine umbrella. "
            "The result installs and runs as-is; edit `run` to do something useful."
        )
        parser.add_argument("--verb", help="the verb as typed (default: the directory name)")
        parser.add_argument(
            "--distribution", help="distribution name (default: the directory name)"
        )
        parser.add_argument(
            "--module", help="import package name (default: the distribution, `-` as `_`)"
        )
        parser.add_argument(
            "--description",
            default="A verb contributed to the astro-mine umbrella CLI.",
            help="one-line package description",
        )

    def run(self, args: argparse.Namespace) -> int:
        target = Path(args.output)
        distribution = args.distribution or target.name
        module = args.module or re.sub(r"[-.]", "_", distribution)
        verb = args.verb or re.sub(r"[_.]", "-", distribution).lower()

        for value, pattern, what in (
            (distribution, _DISTRIBUTION_RE, "distribution name"),
            (verb, _VERB_RE, "verb"),
        ):
            if not pattern.fullmatch(value):
                print(
                    f"astro-mine plugin new cli: {value!r} is not a usable {what}; "
                    f"pass --{what.split()[0]} explicitly",
                    file=sys.stderr,
                )
                return _USAGE_ERROR
        if not module.isidentifier() or keyword.iskeyword(module):
            print(
                f"astro-mine plugin new cli: {module!r} is not a usable Python package name; "
                f"pass --module explicitly",
                file=sys.stderr,
            )
            return _USAGE_ERROR

        files = {
            target / "pyproject.toml": _pyproject(
                distribution=distribution, module=module, verb=verb, description=args.description
            ),
            target / "src" / module / "__init__.py": _module(
                verb=verb, description=args.description
            ),
        }
        existing = [path for path in files if path.exists()]
        if existing and not args.force:
            listing = ", ".join(str(path) for path in existing)
            print(f"{listing}: file exists (use --force to overwrite)", file=sys.stderr)
            return 1

        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
        print(f"\nInstall it and the verb is live:\n  pip install -e {target}\n  astro-mine {verb}")
        return 0


def _symbol(verb: str) -> str:
    """The module-level name the entry point resolves to — a verb is not always an identifier."""
    return re.sub(r"[-.]", "_", verb)


CLI_PLUGIN_SCAFFOLD = _CliPluginScaffold()
