# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astro_mine/allocate/model/ir/_proto/allocation_ir.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'astro_mine/allocate/model/ir/_proto/allocation_ir.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7astro_mine/allocate/model/ir/_proto/allocation_ir.proto\x12\x16\x61stro_mine.allocate.v0\"\xf9\x01\n\x10\x44\x65\x63isionVariable\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04kind\x18\x02 \x01(\tR\x04kind\x12\x19\n\x05lower\x18\x03 \x01(\x01H\x00R\x05lower\x88\x01\x01\x12\x19\n\x05upper\x18\x04 \x01(\x01H\x01R\x05upper\x88\x01\x01\x12\x1a\n\x08semantic\x18\x05 \x01(\tR\x08semantic\x12\x1e\n\x08task_ref\x18\x06 \x01(\tH\x02R\x07taskRef\x88\x01\x01\x12 \n\tasset_ref\x18\x07 \x01(\tH\x03R\x08\x61ssetRef\x88\x01\x01\x42\x08\n\x06_lowerB\x08\n\x06_upperB\x0b\n\t_task_refB\x0c\n\n_asset_ref\"K\n\x0e\x43onstraintTerm\x12\x17\n\x07var_ref\x18\x01 \x01(\tR\x06varRef\x12 \n\x0b\x63oefficient\x18\x02 \x01(\x01R\x0b\x63oefficient\"\x96\x01\n\nConstraint\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04kind\x18\x02 \x01(\tR\x04kind\x12<\n\x05terms\x18\x03 \x03(\x0b\x32&.astro_mine.allocate.v0.ConstraintTermR\x05terms\x12\x14\n\x05sense\x18\x04 \x01(\tR\x05sense\x12\x10\n\x03rhs\x18\x05 \x01(\x01R\x03rhs\"Z\n\rObjectiveTerm\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n\x07var_ref\x18\x02 \x01(\tR\x06varRef\x12 \n\x0b\x63oefficient\x18\x03 \x01(\x01R\x0b\x63oefficient\"\xc1\x03\n\x0c\x41llocationIR\x12\x1d\n\nir_version\x18\x01 \x01(\tR\tirVersion\x12\x46\n\tvariables\x18\x02 \x03(\x0b\x32(.astro_mine.allocate.v0.DecisionVariableR\tvariables\x12\x44\n\x0b\x63onstraints\x18\x03 \x03(\x0b\x32\".astro_mine.allocate.v0.ConstraintR\x0b\x63onstraints\x12N\n\x0fobjective_terms\x18\x04 \x03(\x0b\x32%.astro_mine.allocate.v0.ObjectiveTermR\x0eobjectiveTerms\x12\'\n\x0fobjective_sense\x18\x05 \x01(\tR\x0eobjectiveSense\x12N\n\x08metadata\x18\x06 \x03(\x0b\x32\x32.astro_mine.allocate.v0.AllocationIR.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astro_mine.allocate.model.ir._proto.allocation_ir_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLOCATIONIR_METADATAENTRY']._loaded_options = None
  _globals['_ALLOCATIONIR_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DECISIONVARIABLE']._serialized_start=84
  _globals['_DECISIONVARIABLE']._serialized_end=333
  _globals['_CONSTRAINTTERM']._serialized_start=335
  _globals['_CONSTRAINTTERM']._serialized_end=410
  _globals['_CONSTRAINT']._serialized_start=413
  _globals['_CONSTRAINT']._serialized_end=563
  _globals['_OBJECTIVETERM']._serialized_start=565
  _globals['_OBJECTIVETERM']._serialized_end=655
  _globals['_ALLOCATIONIR']._serialized_start=658
  _globals['_ALLOCATIONIR']._serialized_end=1107
  _globals['_ALLOCATIONIR_METADATAENTRY']._serialized_start=1048
  _globals['_ALLOCATIONIR_METADATAENTRY']._serialized_end=1107
# @@protoc_insertion_point(module_scope)
