# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astro_mine/guard/audit/_proto/safety_verdict.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'astro_mine/guard/audit/_proto/safety_verdict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2astro_mine/guard/audit/_proto/safety_verdict.proto\x12\x19\x61stro_mine.guard.audit.v0\"\xbd\x05\n\rSafetyVerdict\x12\'\n\x0fverdict_version\x18\x01 \x01(\tR\x0everdictVersion\x12\x19\n\x08\x61gent_id\x18\x02 \x01(\tR\x07\x61gentId\x12\x12\n\x04tick\x18\x03 \x01(\x03R\x04tick\x12\x1c\n\nsim_time_s\x18\x04 \x01(\x01R\x08simTimeS\x12\x17\n\x07spec_id\x18\x05 \x01(\tR\x06specId\x12*\n\x11spec_content_hash\x18\x06 \x01(\tR\x0fspecContentHash\x12\x32\n\x15\x63ompiled_content_hash\x18\x07 \x01(\tR\x13\x63ompiledContentHash\x12,\n\x12guard_code_version\x18\x08 \x01(\tR\x10guardCodeVersion\x12\x14\n\x05layer\x18\t \x01(\tR\x05layer\x12\"\n\x0cintervention\x18\n \x01(\tR\x0cintervention\x12\x16\n\x06reason\x18\x0b \x01(\tR\x06reason\x12$\n\x0b\x62\x61\x63kup_kind\x18\x0c \x01(\tH\x00R\nbackupKind\x88\x01\x01\x12%\n\x0e\x63onstraint_ids\x18\r \x03(\tR\rconstraintIds\x12)\n\x10\x63\x65rtified_action\x18\x0e \x03(\x01R\x0f\x63\x65rtifiedAction\x12,\n\x12min_barrier_margin\x18\x0f \x01(\x01R\x10minBarrierMargin\x12+\n\x11\x61\x63tion_divergence\x18\x10 \x01(\x01R\x10\x61\x63tionDivergence\x12.\n\x13inputs_content_hash\x18\x11 \x01(\tR\x11inputsContentHash\x12*\n\x11shield_latency_us\x18\x12 \x01(\x01R\x0fshieldLatencyUsB\x0e\n\x0c_backup_kindb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astro_mine.guard.audit._proto.safety_verdict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAFETYVERDICT']._serialized_start=82
  _globals['_SAFETYVERDICT']._serialized_end=783
# @@protoc_insertion_point(module_scope)
