"""Worlds' scaffold for the umbrella CLI — `astro-mine plugin new field-model`.

RFC-0011 §7 puts the scaffolding *verb* in the umbrella, because scaffolding spans components and
has no single-component home. It leaves the *template* with whoever hosts the extension group, and
``astro_mine.field_models`` is Worlds'.

**Which backend answers "is the Sun visible here, at this epoch?" is a WorldSpec choice, not a code
path** (`worlds.md §3`). This scaffold is how a third party joins that set. Three things the
template has to get right, each of which the registry enforces and none of which is guessable:

1. **The entry-point name is the backend id**, selectable from a ``WorldSpec``'s
   ``layers.illumination_backend`` — which is how a whole world bundle picks up a backend.
2. **A built-in id may not be shadowed.** Advertising ``horizon``, ``raycast_cpu``, ``raycast_gpu``
   or ``surrogate`` is a hard error naming both claimants, because a backend id is *provenance*: it
   is folded into ``illumination_hash`` and stamped into the published ``field_model`` manifest, so
   an ambiguous id would mis-attribute which model produced an illumination product. The scaffold
   refuses a shadowing id rather than emitting a package that fails at resolution.
3. **The horizon map stays.** A finer Sun-visibility backend does not remove the per-azimuth skyline
   Link queries for occlusion (`worlds.md §6`) — it is the always-present LOS product. Subclassing
   the shipped model is the cheap way to inherit it, and the template does exactly that.

**Nothing here imports the umbrella.** The contract is structural — ``name``, ``help``,
``add_arguments(parser)``, ``run(args) -> int`` — the same four members a verb has.
``astro-mine-cli`` is not a dependency of this package and must not become one.
"""

from __future__ import annotations

import argparse
import keyword
import re
import sys
from pathlib import Path

__all__ = ["field_model_scaffold"]

_USAGE_ERROR = 2


def _pyproject(*, distribution: str, module: str, backend: str) -> str:
    return f"""\
# Generated by `astro-mine plugin new field-model`.
#
# Install this package and `{backend}` becomes selectable — from the illumination registry, and from
# a WorldSpec's `layers.illumination_backend`, which is how a whole world bundle picks it up.
# Nothing has to be registered anywhere else, and no Astro-Mine repo has to change.
#
# The entry-point NAME is the backend id. It is provenance: it is folded into `illumination_hash`
# and stamped into the published `field_model` manifest, so it must not shadow a built-in.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{distribution}"
version = "0.1.0"
description = "An illumination backend contributed to Astro-Mine-Worlds."
requires-python = ">=3.12"
# Note what is NOT here: astro-mine-cli. The umbrella loads this package; it is not a dependency
# of it.
dependencies = ["astro-mine-worlds"]

[project.entry-points."astro_mine.field_models"]
{backend} = "{module}:build"

[tool.hatch.build.targets.wheel]
packages = ["src/{module}"]
"""


def _module(*, backend: str, symbol: str) -> str:
    return f'''\
"""An illumination backend for Astro-Mine-Worlds — the `{backend}` field model.

Generated by `astro-mine plugin new field-model`.

**The contract** is a factory ``(terrain, **kwargs) -> SunVisibilityModel``: a structural Protocol
covering ``sun_visible`` / ``illumination_at`` / ``illuminated_mask`` / ``psr_mask``, plus the
attributes a provider reads through the model. You inherit nothing from Worlds by requirement — only
the shape matters — but subclassing the shipped model is the cheap way to start, because of the next
paragraph.

**The horizon map stays.** A finer Sun-visibility backend does not remove the per-azimuth skyline
Link queries for line-of-sight occlusion: it is the always-present product, not an implementation
detail of the default backend. Serve it or inherit it. Subclassing `IlluminationModel` inherits it,
which is why this template starts there and overrides only the query it means to change.

**Your id is provenance.** It is folded into `illumination_hash` and stamped into the published
`field_model` manifest, so an illumination product can always be attributed to the model that
produced it. That is also why the registry refuses to let you shadow a built-in id.
"""

from __future__ import annotations

from typing import Any

from astro_mine.worlds.illumination import IlluminationModel


class {symbol}(IlluminationModel):
    """Starts as the shipped horizon-map model, so it answers every query from the first commit.

    Override what you actually improve and leave the rest — in particular, leave the `horizon` map
    intact unless you are serving your own.
    """

    def sun_visible(self, x: float, y: float, epoch: Any) -> bool:
        """Is the Sun above the terrain horizon at projected ``(x, y)``, at ``epoch``?

        Replace this with your backend's answer. Delegating for now keeps the model correct while
        you wire the rest up.
        """
        return super().sun_visible(x, y, epoch)


def build(terrain: Any, **kwargs: Any) -> {symbol}:
    """The entry-point factory the registry calls: ``(terrain, **kwargs) -> SunVisibilityModel``.

    Extra kwargs (``n_azimuth``, ``max_radius_m``, ...) flow through unchanged, so selecting this
    backend is a drop-in for the default.
    """
    return {symbol}(terrain, **kwargs)
'''


class _FieldModelScaffold:
    """`astro-mine plugin new field-model <dir>` — a package registering an illumination backend."""

    name = "field-model"
    help = "an illumination backend (astro_mine.field_models)"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.description = (
            "Scaffold a package that contributes an illumination backend to Worlds. The "
            "entry-point name is the backend id — it is provenance, and it may not shadow a "
            "built-in."
        )
        parser.add_argument(
            "--backend",
            default="demo-illum",
            help="the backend id, as selected from a WorldSpec (default: demo-illum)",
        )
        parser.add_argument("--distribution", help="distribution name (default: directory name)")
        parser.add_argument("--module", help="import package (default: distribution, `-` as `_`)")

    def run(self, args: argparse.Namespace) -> int:
        from astro_mine.worlds.illumination._registry import _BUILTINS

        target = Path(args.output)
        distribution = args.distribution or target.name
        module = args.module or re.sub(r"[-.]", "_", distribution)
        backend = args.backend

        if backend in _BUILTINS:
            print(
                f"astro-mine plugin new field-model: {backend!r} is a built-in backend id and "
                f"cannot be shadowed — advertising it is a hard error naming both claimants, "
                f"because a backend id is provenance (it is folded into illumination_hash). "
                f"Pick your own id with --backend.",
                file=sys.stderr,
            )
            return _USAGE_ERROR
        if not module.isidentifier() or keyword.iskeyword(module):
            print(
                f"astro-mine plugin new field-model: {module!r} is not a usable Python package "
                f"name; pass --module explicitly",
                file=sys.stderr,
            )
            return _USAGE_ERROR

        symbol = "".join(part.title() for part in re.split(r"[-._]", backend) if part) + "Model"
        files = {
            target / "pyproject.toml": _pyproject(
                distribution=distribution, module=module, backend=backend
            ),
            target / "src" / module / "__init__.py": _module(backend=backend, symbol=symbol),
        }
        existing = [path for path in files if path.exists()]
        if existing and not args.force:
            listing = ", ".join(str(path) for path in existing)
            print(f"{listing}: file exists (use --force to overwrite)", file=sys.stderr)
            return 1
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
        print(
            f"\nInstall it and the id becomes selectable:\n  pip install -e {target}\n"
            f"  # then, from a WorldSpec: layers.illumination_backend: {backend}"
        )
        return 0


field_model_scaffold = _FieldModelScaffold()
