# SPDX-License-Identifier: Apache-2.0
"""Canonical JSON Schema for the surrogate contracts (surrogate.md §5; conventions.md §3).

The Pydantic models are the source of truth; this exports their JSON Schema so an
external / cross-language consumer has a first-class, checked-in schema. The schema files
under ``schema/`` are generated by ``scripts/export_schemas.py`` from exactly this
function, and ``tests/test_schema.py`` regenerates-and-compares as the drift guard — the
same "one schema, kept in lockstep with the typed model" convention Core follows.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from astro_mine.surrogate.manifest import SurrogateAttributes
from astro_mine.surrogate.report import ErrorReport

__all__ = ["SCHEMA_BASE_URL", "json_schemas"]

#: The ``$id`` base for the surrogate schemas — mirrors Core's ``schemas.astro-mine.org``
#: namespace and the per-interface ``v0.1`` scheme.
SCHEMA_BASE_URL = "https://schemas.astro-mine.org/surrogate/v0.1"


def _with_meta(model: type[BaseModel], slug: str) -> dict[str, Any]:
    schema = model.model_json_schema()
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{SCHEMA_BASE_URL}/{slug}.schema.json",
        **schema,
    }


def json_schemas() -> dict[str, dict[str, Any]]:
    """Map each canonical schema filename to its JSON Schema document.

    The single definition both ``scripts/export_schemas.py`` (which writes the files) and
    the drift-guard test consume, so the checked-in files can never silently diverge from
    the models.
    """
    return {
        "error_report.schema.json": _with_meta(ErrorReport, "error-report"),
        "surrogate_attributes.schema.json": _with_meta(SurrogateAttributes, "surrogate-attributes"),
    }
