#!/usr/bin/env python
"""Assemble the content-addressed Core schema bundle (RM-P0-CORE-08).

Core's distribution artifact for private incubation is a versioned, **content-addressed
schema bundle** published as an OCI artifact to private GHCR (``docs/VERSIONING.md`` §5;
``core.md`` §7). This script stages that bundle deterministically and computes its
identity so a Bench run — or any downstream consumer — can pin *the exact Core schema
version by digest*.

What goes in the bundle:

- the canonical **JSON Schemas** (SADF, ObjectiveSpec, message catalog, plugin manifest),
- the **Cap'n Proto** hot-path schema,
- the canonical **Protobuf** sources (the wire form, regenerated by ``buf`` downstream),
- optionally (``--clients-dir``) the **generated per-language clients** (C++/Rust/TS),
  which ride along as a convenience but are *not* part of the pinnable identity.

The **schema digest** (``sha256:…``) is computed over the canonical schema *sources*
only — a sha256 of the sorted ``"<sha256>  <relpath>"`` manifest. It is therefore
reproducible: the same schemas always yield the same digest, independent of the package
version, the source commit, filesystem ordering, or whether clients were bundled. That
digest is what ``ScenarioSpec`` pins (``VERSIONING.md`` §4.2; CX-REPRO).

Usage::

    uv run python scripts/build_schema_bundle.py                 # -> dist/schema-bundle
    uv run python scripts/build_schema_bundle.py --out b --clients-dir codegen

Writes ``bundle.json`` (metadata + per-file hashes + ``schema_digest``),
``MANIFEST.sha256`` (``sha256sum -c``-verifiable), and ``SCHEMA_DIGEST`` (the bare
digest, for CI to read without a JSON parser). Prints the digest as its last line.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
PROTO_ROOT = ROOT / "schemas" / "proto"


def _ensure_core_importable() -> None:
    """Import ``astro_mine`` from ``src/`` — the tree we are bundling, not an installed copy."""
    if str(SRC) not in sys.path:
        sys.path.insert(0, str(SRC))


def _json_schemas() -> list[str]:
    """Canonical JSON Schemas as paths relative to ``src/``, derived from the package.

    ``astro_mine.core.schemas.CORE_JSON_SCHEMAS`` is the **single declaration** of the Core
    schema set — the same tuple ``schema_registry()`` resolves from. Deriving the bundle list
    from it instead of keeping a second copy is the point: four hand-maintained inventories of
    this set drifted apart before anything reconciled them (#50, #52), and a fifth would have
    been this one (RFC-0009)."""
    _ensure_core_importable()
    from astro_mine.core.schemas import CORE_JSON_SCHEMAS

    return [f"{pkg.replace('.', '/')}/schema/{name}" for pkg, name in CORE_JSON_SCHEMAS]


#: Canonical JSON Schemas (paths relative to ``src/``). The schema is the source of
#: truth; the hand-written Pydantic models track it (``scripts/check_model_drift.py``).
JSON_SCHEMAS = _json_schemas()

#: Cap'n Proto schema for the per-tick hot-path observation family (conventions.md §3).
CAPNP_SCHEMAS = [
    "astro_mine/core/messages/schema/observation.capnp",
]

#: Shared conformance vectors (RFC-0007; RM-P1-CORE-08) — the data form of the units guard
#: contract tests every binding runs. Part of the pinnable schema identity so a consumer
#: pins the exact vectors it validated against.
CONFORMANCE_VECTORS = [
    "astro_mine/core/units/schema/conformance.json",
]

#: Schema sources deliberately kept *out* of the bundle, mapped to the reason. Empty
#: today — every schema source ships. The lists above are hand-maintained (unlike the
#: ``.proto`` sources, which are globbed and so cannot drift), and ``plan.schema.json``
#: shipped a whole release cycle outside the bundle because nothing reconciled them
#: against the tree. A schema source that is in no list above and not excused here is
#: *undeclared*, and ``tests/test_schema_bundle.py`` fails on it.
BUNDLE_EXCLUDED: dict[str, str] = {}

#: The search space the drift guard reconciles the declared lists against: schemas ship
#: in-package, one ``schema/`` directory per component (``schemas/json/README.md``).
SCHEMA_SOURCE_GLOB = "astro_mine/core/*/schema/*"

#: Generated per-language clients, mapped ``<codegen subdir> -> <bundle subdir>``. These
#: are convenience payload, excluded from ``schema_digest`` (see module docstring).
CLIENT_DIRS = {
    "cpp/generated": "clients/cpp",
    "rust/generated": "clients/rust",
    "ts/generated": "clients/ts",
}

#: Bundle-format version — bump on a *breaking* change to the on-disk layout or metadata
#: shape. Additive keys (``schema_index``) do not bump it: the bundle follows the same
#: additive/append-only/never-break rule as the rest of the Core contract
#: (``VERSIONING.md`` §4), so a reader of an older format keeps working.
BUNDLE_FORMAT = "astro-mine-core/schema-bundle/v1"


@dataclass(frozen=True)
class BundleFile:
    """One file staged into the bundle: where it comes from, where it lands."""

    source: Path
    relpath: str  # POSIX path inside the bundle


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def collect_schema_files() -> list[BundleFile]:
    """The canonical schema sources, in a stable (path-sorted) order. Fails loud if a
    declared schema is missing — a renamed/removed schema must be reflected here."""
    files: list[BundleFile] = []
    for rel in JSON_SCHEMAS:
        src = SRC / rel
        if not src.is_file():
            raise FileNotFoundError(f"declared JSON Schema not found: {src}")
        files.append(BundleFile(src, f"schemas/json/{src.name}"))
    for rel in CAPNP_SCHEMAS:
        src = SRC / rel
        if not src.is_file():
            raise FileNotFoundError(f"declared Cap'n Proto schema not found: {src}")
        files.append(BundleFile(src, f"schemas/capnp/{src.name}"))
    for rel in CONFORMANCE_VECTORS:
        src = SRC / rel
        if not src.is_file():
            raise FileNotFoundError(f"declared conformance vectors not found: {src}")
        files.append(BundleFile(src, f"schemas/conformance/{src.name}"))
    protos = sorted(PROTO_ROOT.rglob("*.proto"))
    if not protos:
        raise FileNotFoundError(f"no .proto sources under {PROTO_ROOT}")
    for src in protos:
        rel = src.relative_to(PROTO_ROOT).as_posix()
        files.append(BundleFile(src, f"schemas/proto/{rel}"))
    return sorted(files, key=lambda f: f.relpath)


def declared_schema_sources() -> set[str]:
    """Every schema source the bundle declares, as paths relative to ``src/``."""
    return {*JSON_SCHEMAS, *CAPNP_SCHEMAS, *CONFORMANCE_VECTORS}


def discover_schema_sources() -> set[str]:
    """Every schema source on disk, as paths relative to ``src/``."""
    return {p.relative_to(SRC).as_posix() for p in SRC.glob(SCHEMA_SOURCE_GLOB) if p.is_file()}


def undeclared_schema_sources() -> set[str]:
    """Schema sources on disk that no list declares and no :data:`BUNDLE_EXCLUDED` excuses.

    The converse of :func:`collect_schema_files`, which fails loud when a *declared*
    schema is missing from disk. Together the two pin the declared lists to the tree in
    both directions, so a schema can neither vanish from under the bundle nor — the
    RFC-0006 ``plan`` case — be added to Core without ever reaching it."""
    return discover_schema_sources() - declared_schema_sources() - set(BUNDLE_EXCLUDED)


def collect_client_files(clients_dir: Path) -> list[BundleFile]:
    """Generated language clients found under ``clients_dir`` (a ``codegen/`` tree).
    Silently skips a language whose generated dir is absent (e.g. codegen not run)."""
    files: list[BundleFile] = []
    for sub, dest in CLIENT_DIRS.items():
        root = clients_dir / sub
        if not root.is_dir():
            continue
        for src in sorted(p for p in root.rglob("*") if p.is_file()):
            rel = src.relative_to(root).as_posix()
            files.append(BundleFile(src, f"{dest}/{rel}"))
    return sorted(files, key=lambda f: f.relpath)


def _hash_pairs(files: list[BundleFile]) -> list[tuple[str, str]]:
    """``(relpath, sha256)`` pairs, path-sorted — the manifest's canonical form."""
    return sorted((f.relpath, _sha256(f.source)) for f in files)


def schema_digest(files: list[BundleFile]) -> str:
    """Reproducible bundle identity: sha256 over the sorted ``"<sha256>  <relpath>"``
    manifest of the schema sources. Independent of version/commit/ordering.

    The algorithm lives in the package (``astro_mine.core.hashing.manifest_digest``) so this
    script and the shipped :data:`astro_mine.core.SCHEMA_DIGEST` constant are the *same*
    computation — not two that must agree byte-for-byte and silently could not."""
    _ensure_core_importable()
    from astro_mine.core.hashing import manifest_digest

    return manifest_digest((f.relpath, f.source.read_bytes()) for f in files)


def _stage(files: list[BundleFile], out: Path) -> None:
    for f in files:
        dest = out / f.relpath
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(f.source, dest)  # content only — no mtimes, for reproducibility


def schema_index(files: list[BundleFile]) -> dict[str, str]:
    """``{"<$id>": "<bundle relpath>"}`` for every JSON Schema that declares an ``$id``.

    What makes the bundle **self-sufficient**. The schemas ``$ref`` each other across files
    by absolute ``$id`` (RFC-0007: messages/mission reference the shared units vocabulary),
    and those ``$id`` URIs are nominal — nothing serves them, and resolution must work
    offline (``conventions.md``). Without a map from ``$id`` to the file carrying it, a
    consumer cannot resolve those refs and Core's own registry wiring is the only way in —
    which is Python, and not shipped here. With it, any validator can register each schema
    under its ``$id`` and deep-validate with no Core-specific knowledge (#53)."""
    index: dict[str, str] = {}
    for f in files:
        if not f.relpath.startswith("schemas/json/"):
            continue
        doc = json.loads(f.source.read_text(encoding="utf-8"))
        schema_id = doc.get("$id")
        if schema_id:
            index[str(schema_id)] = f.relpath
    return index


#: The generated module carrying the digest into the installed package. Committed to git and
#: guarded by ``tests/test_schema_digest.py`` — see :func:`write_digest_module`.
DIGEST_MODULE = SRC / "astro_mine" / "core" / "_schema_digest.py"

_DIGEST_MODULE_TEMPLATE = '''\
"""The Core schema digest — GENERATED, do not edit by hand.

Regenerate with::

    uv run python scripts/build_schema_bundle.py --update-digest

The digest is computed over the *full* schema source set — including the ``.proto`` sources
under ``schemas/proto/``, which live at the repo root and are **not** packaged in the wheel.
That is why this is a committed constant rather than something recomputed at import time: an
installed Core cannot see those files, so it could not reproduce the digest if it tried, and
a filesystem walk relative to ``__file__`` would yield a plausible-but-wrong value in a wheel
while looking perfectly correct in this repo (#55).
"""

SCHEMA_DIGEST = "{digest}"
'''


def write_digest_module(digest: str) -> bool:
    """Write :data:`DIGEST_MODULE` with ``digest``. Returns True if the file changed."""
    text = _DIGEST_MODULE_TEMPLATE.format(digest=digest)
    if DIGEST_MODULE.is_file() and DIGEST_MODULE.read_text(encoding="utf-8") == text:
        return False
    DIGEST_MODULE.write_text(text, encoding="utf-8")
    return True


def packaged_digest() -> str | None:
    """:data:`astro_mine.core.SCHEMA_DIGEST` as the source tree currently ships it.

    ``None`` when the constant is absent — the publish workflow restores this builder onto
    tags cut before the constant existed, and those must still bundle."""
    _ensure_core_importable()
    try:
        from astro_mine.core import SCHEMA_DIGEST
    except ImportError:
        return None
    return str(SCHEMA_DIGEST)


def _core_metadata(version: str | None) -> tuple[str, dict[str, str]]:
    """Resolve ``(core_version, interface_versions)`` from the installed/sourced package.
    ``--version`` overrides the package version (the publish workflow passes the tag)."""
    _ensure_core_importable()
    import astro_mine.core as core
    from astro_mine.core.compat import CORE_INTERFACE_VERSIONS

    return version or core.__version__, dict(CORE_INTERFACE_VERSIONS)


def build(
    out: Path,
    *,
    clients_dir: Path | None = None,
    version: str | None = None,
    commit: str | None = None,
) -> str:
    """Stage the bundle into ``out`` and return its ``schema_digest``."""
    schema_files = collect_schema_files()
    client_files = collect_client_files(clients_dir) if clients_dir else []
    digest = schema_digest(schema_files)
    core_version, interface_versions = _core_metadata(version)

    # Fail closed: the bundle we publish and the digest the package *claims* to carry must be
    # the same value. A stale constant would have consumers pinning a digest no bundle has.
    shipped = packaged_digest()
    if shipped is not None and shipped != digest:
        raise SystemExit(
            f"astro_mine.core.SCHEMA_DIGEST is stale: package says {shipped}, schemas hash to "
            f"{digest}.\nRegenerate it: uv run python scripts/build_schema_bundle.py "
            "--update-digest"
        )

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    _stage(schema_files, out)
    _stage(client_files, out)

    meta = {
        "format": BUNDLE_FORMAT,
        "name": "astro-mine-core-schemas",
        "core_version": core_version,
        "source_commit": commit,
        "interface_versions": interface_versions,
        "schema_digest": digest,
        "schema_index": schema_index(schema_files),
        "files": [{"path": rel, "sha256": sha} for rel, sha in _hash_pairs(schema_files)],
        "clients": [{"path": rel, "sha256": sha} for rel, sha in _hash_pairs(client_files)],
    }
    (out / "bundle.json").write_text(
        json.dumps(meta, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    # `sha256sum -c MANIFEST.sha256` (run from the bundle root) re-verifies every file,
    # covering clients too so a tampered client payload is caught.
    all_pairs = _hash_pairs(schema_files + client_files)
    (out / "MANIFEST.sha256").write_text(
        "".join(f"{sha}  {rel}\n" for rel, sha in all_pairs), encoding="utf-8"
    )
    (out / "SCHEMA_DIGEST").write_text(digest + "\n", encoding="utf-8")
    return digest


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the Core schema bundle.")
    parser.add_argument(
        "--out", type=Path, default=ROOT / "dist" / "schema-bundle", help="output directory"
    )
    parser.add_argument(
        "--clients-dir",
        type=Path,
        default=None,
        help="codegen/ tree to fold generated C++/Rust/TS clients in from (optional)",
    )
    parser.add_argument("--version", default=None, help="override core version (e.g. the Git tag)")
    parser.add_argument("--commit", default=None, help="source commit SHA to record in bundle.json")
    parser.add_argument(
        "--update-digest",
        action="store_true",
        help="regenerate src/astro_mine/core/_schema_digest.py and exit (no bundle staged)",
    )
    args = parser.parse_args()

    if args.update_digest:
        digest = schema_digest(collect_schema_files())
        changed = write_digest_module(digest)
        verb = "Updated" if changed else "Already current"
        print(f"{verb}: {DIGEST_MODULE.relative_to(ROOT)} — SCHEMA_DIGEST = {digest}")
        return 0

    digest = build(args.out, clients_dir=args.clients_dir, version=args.version, commit=args.commit)
    n_schemas = len(collect_schema_files())
    n_clients = len(collect_client_files(args.clients_dir)) if args.clients_dir else 0
    print(f"Bundle staged at {args.out} — {n_schemas} schema files, {n_clients} client files.")
    print(f"Schema digest: {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
