#!/usr/bin/env python
"""Render Sim's workload Dockerfile through Cloud's packaging discipline (RM-P0-CLOUD-01).

RM-P0-CLOUD-01 requires container-first, **digest-pinned** packaging of every P0 workload and names
Sim explicitly; ``cloud.md`` §12 says how. Sim adopts that machinery rather than hand-rolling a
Dockerfile: :class:`astro_mine.cloud.packaging.BuildSpec` +
:func:`~astro_mine.cloud.packaging.render_dockerfile` produce the workload stage, and
:class:`~astro_mine.cloud.packaging.ImageRef` is the digest-pinned reference a Bench/Cloud job spec
resolves the image by.

The rendered file has three parts, and only the middle one is ours to obey rather than write:

1. a **builder** stage (Sim-owned) that resolves the locked dependency set into a venv — Cloud's
   template deliberately carries no ``COPY``/``RUN``, so the app has to come from somewhere;
2. the **workload** stage, emitted *verbatim* by ``render_dockerfile`` — a base pinned by digest, a
   fixed ``SOURCE_DATE_EPOCH``, the OCI annotations, ``USER 65532:65532`` (non-root), and the
   entrypoint. A test asserts this block appears byte-for-byte, so the discipline is provably
   Cloud's;
3. the **payload** copy of that venv into the workload stage.

The result is committed (``docker/Dockerfile``) and gated against drift by
``tests/test_packaging.py``.
Regenerate after changing the spec:

    uv run python scripts/render_dockerfile.py            # write docker/Dockerfile
    uv run python scripts/render_dockerfile.py --check    # fail if it would change (CI)
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from astro_mine.cloud.packaging import BuildSpec, ImageRef, render_dockerfile

_REPO_ROOT = Path(__file__).resolve().parent.parent
DOCKERFILE = _REPO_ROOT / "docker" / "Dockerfile"

#: The base image, pinned by **digest** — never a floating tag (RM-P0-CLOUD-01; conventions.md §7).
#: A tag is mutable: `python:3.12-slim` is a different image next month, so a "reproducible" build
#: on
#: a tag is not reproducible at all. This digest is `python:3.12-slim` as of 2026-07-11.
BASE_IMAGE = (
    "docker.io/library/python@sha256:"
    "423ed6ab25b1921a477529254bfeeabf5855151dc2c3141699a1bfc852199fbf"
)

#: Where the workload image is published. Bench/Cloud job specs resolve it by an `ImageRef` content
#: hash (`repository@sha256:...`), so a job always starts from the exact bytes it was scored
#: against.
REPOSITORY = "ghcr.io/astro-mine/astro-mine-sim"

#: A fixed build clock, so the image metadata is byte-stable across builds (cloud.md §4 principle
#: 4).
SOURCE_DATE_EPOCH = 0


def build_spec(*, version: str = "0.1.0", revision: str | None = None) -> BuildSpec:
    """The `BuildSpec` Sim's workload image is rendered from."""
    return BuildSpec(
        base=ImageRef.parse(BASE_IMAGE),
        repository=REPOSITORY,
        version=version,
        # A Cloud job runs a scenario; `python -m astro_mine.sim` is the runner (see __main__.py).
        entrypoint=["python", "-m", "astro_mine.sim"],
        source_date_epoch=SOURCE_DATE_EPOCH,
        revision=revision,
        title="astro-mine-sim",
        labels={
            # A URL, per the OCI spec -- and the repository that ships the code, not the
            # archived one this image was named after.
            "org.opencontainers.image.source": "https://github.com/astro-mine/astro-mine-platform",
            "org.opencontainers.image.description": (
                "Astro-Mine-Sim — multi-physics engine and scenario runtime."
            ),
            "org.opencontainers.image.licenses": "Apache-2.0",
        },
    )


_BUILDER_STAGE = rf"""# syntax=docker/dockerfile:1
#
# Astro-Mine-Sim workload image (RM-P0-CLOUD-01; cloud.md §12).
#
# GENERATED by `scripts/render_dockerfile.py` -- do not hand-edit; regenerate it. The workload
# stage below is emitted verbatim by `astro_mine.cloud.packaging.render_dockerfile`, so Sim
# *adopts* Cloud's packaging discipline rather than re-implementing it; `tests/test_packaging.py`
# gates the drift.
#
# --- builder: resolve the locked dependency set into a venv ---------------------------------------
#
# Cloud's workload template carries no COPY/RUN by design (it is a metadata + entrypoint wrapper
# over a pre-baked base), so the application layer is built here and copied into the workload stage
# below. This stage is discarded, so nothing it installs (git, the uv binary, the token) ships.
#
# The base is pinned by DIGEST here too, exactly as the workload stage's is: a floating tag in the
# builder would make the resolved dependency set irreproducible just as surely as one in the
# workload.
FROM {BASE_IMAGE} AS builder

COPY --from=ghcr.io/astral-sh/uv:0.9.9 /uv /usr/local/bin/uv

# git resolves the private astro-mine-* git dependencies during incubation. Drop it (and the token
# mount below) after the public/PyPI flip.
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY pyproject.toml uv.lock README.md ./
COPY src ./src

# `--locked` fails rather than re-resolving: the lockfile is the reproducibility contract
# (conventions.md §7). `--no-dev` keeps the test/lint toolchain out of the shipped image. The PAT
# arrives as a build *secret*, so it never lands in a layer.
RUN --mount=type=secret,id=core_token \
    sh -c 'if [ -f /run/secrets/core_token ]; then \
      git config --global \
        url."https://x-access-token:$(cat /run/secrets/core_token)@github.com/".insteadOf \
        "https://github.com/"; \
    fi' \
    && uv sync --locked --no-dev --no-editable

# --- workload: generated verbatim by astro_mine.cloud.packaging.render_dockerfile -----------------
"""

_PAYLOAD = r"""
# --- payload: the resolved venv from the builder stage --------------------------------------------
# Owned by the non-root uid the workload stage runs as, so the image needs no privilege to read it.
COPY --from=builder --chown=65532:65532 /app/.venv /app/.venv

# Put the venv's interpreter first on PATH, so the ENTRYPOINT's bare `python` is *this* environment.
ENV PATH="/app/.venv/bin:$PATH" \
    VIRTUAL_ENV="/app/.venv" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
"""


def render(*, version: str = "0.1.0", revision: str | None = None) -> str:
    """The full workload Dockerfile: builder + the Cloud-rendered workload stage + the payload."""
    return (
        _BUILDER_STAGE
        + render_dockerfile(build_spec(version=version, revision=revision))
        + _PAYLOAD
    )


def _git_revision() -> str | None:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=_REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):  # pragma: no cover  (no git in the sandbox)
        return None
    return out.stdout.strip() or None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="render_dockerfile", description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed Dockerfile differs from what would be rendered",
    )
    args = parser.parse_args(argv)

    # The revision is deliberately NOT baked into the committed file: it would change on every
    # commit
    # and the golden test would never be green. CI passes it at build time instead.
    rendered = render()
    if args.check:
        current = DOCKERFILE.read_text(encoding="utf-8") if DOCKERFILE.exists() else ""
        if current != rendered:
            print(
                f"{DOCKERFILE} is stale — regenerate it with "
                "`uv run python scripts/render_dockerfile.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{DOCKERFILE} is up to date")
        return 0

    DOCKERFILE.parent.mkdir(parents=True, exist_ok=True)
    DOCKERFILE.write_text(rendered, encoding="utf-8")
    print(f"wrote {DOCKERFILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
