"""Bench's scaffold for the umbrella CLI — `astro-mine plugin new runner`.

RFC-0011 §7 puts the scaffolding *verb* in the umbrella, because scaffolding spans components and
has no single-component home. It leaves the *template* with whoever hosts the extension group, and
``astro_mine.bench.runners`` is Bench's.

**This is the platform's best worked example of "contribute once, use everywhere."** Bench scores
against real physics without ever importing Sim — it stays dependency-clean (``core`` +
``pydantic``) — so the Sim-backed runner lives in *Sim*, registers here, and Bench discovers it by
name. A third-party engine joins the same way, and the template exists to make three consequences
visible:

1. **The entry-point name is the ``--runner`` id**, and it is stamped on the scorecard and folded
   into its content hash. A third-party run is therefore distinguishable by *provenance*, not only
   by its numbers — which is what makes accepting an outside runner safe for a benchmark.
2. **``store`` is typed ``object``**, deliberately, so Bench never names a Sim type. A scaffold that
   annotated it with the concrete store would put a Sim import in a package Bench discovers, and
   the emitted plugin would drag Sim onto every machine that installed it.
3. **A runner answers two surfaces**, not one: ``episode_runner`` for the scoring path and
   ``harness_runner`` for the determinism gate. A plugin that implemented only the first installs
   and registers cleanly, and then fails at the gate — which is the run that matters most.

**Nothing here imports the umbrella**, and this module keeps Bench's own dependency rule: it
imports only Bench. The contract is structural — ``name``, ``help``, ``add_arguments(parser)``,
``run(args) -> int``. ``astro-mine-cli`` is not a dependency here and must not become one.
"""

from __future__ import annotations

import argparse
import keyword
import re
import sys
from pathlib import Path

__all__ = ["runner_scaffold"]

_USAGE_ERROR = 2


def _pyproject(*, distribution: str, module: str, runner: str) -> str:
    return f"""\
# Generated by `astro-mine plugin new runner`.
#
# Install this package and `astro-mine-bench score --runner {runner}` works. Nothing has to be
# registered anywhere else, and no Astro-Mine repo has to change.
#
# The entry-point NAME is the --runner id. It is stamped on the scorecard and folded into its
# content hash, so a run made with this runner is distinguishable by provenance rather than only
# by its numbers.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{distribution}"
version = "0.1.0"
description = "A Bench execution backend contributed to Astro-Mine-Bench."
requires-python = ">=3.12"
# Add whatever engine your runner actually drives. Note what is NOT here: astro-mine-cli. The
# umbrella loads this package; it is not a dependency of it.
dependencies = ["astro-mine-bench"]

[project.entry-points."astro_mine.bench.runners"]
{runner} = "{module}:{_symbol(runner)}_runner_provider"

[tool.hatch.build.targets.wheel]
packages = ["src/{module}"]
"""


def _module(*, runner: str) -> str:
    symbol = _symbol(runner)
    return f'''\
"""A Bench execution backend — the `{runner}` runner.

Generated by `astro-mine plugin new runner`.

**The contract** is a ``BenchRunnerProvider``: a ``runner_id`` property, ``episode_runner(store)``
for the scoring path, and ``harness_runner(store)`` for the determinism gate. Answer **both** — a
provider with only the first installs and registers cleanly, then fails at the gate, which is the
run that matters most.

**``store`` is typed ``object`` on purpose.** It is the content store an engine-backed runner reads
(resolved by `astro-mine-bench fetch`), and Bench types it loosely precisely so it never names a Sim
type. Keep the annotation as it is: narrowing it to a concrete store would put an engine import in a
package Bench discovers, and drag that engine onto every machine that installs this one.

**Your id is provenance.** It is stamped on the scorecard and folded into its content hash, which is
what lets a third-party run be told apart from a reference one by more than its numbers.

**Refuse rather than degrade.** If you find you cannot honestly score a scenario — content that did
not resolve, a capability you cannot model — raise ``astro_mine.bench.baseline.ScoringRefused`` with
a message naming what is missing and how to supply it. Bench presents that as an error a user can
act on; anything else you raise is treated as a bug and keeps its traceback. Returning a degraded
trace instead would publish a claim your run cannot support.

    astro-mine-bench score --runner {runner}
"""

from __future__ import annotations

from astro_mine.bench.baseline import fixture_runner_provider


class {symbol.title().replace("_", "")}RunnerProvider:
    """Delegates to the shipped fixture runner, so it scores from the first commit.

    Replace the two methods with your engine's own. Starting from the fixture means the plumbing —
    registration, discovery, the scorecard — is proven before you introduce anything that can fail
    for a reason of its own.
    """

    runner_id = "{runner}"

    def episode_runner(self, store: object | None = None) -> object:
        """The scoring path."""
        return fixture_runner_provider.episode_runner(store)

    def harness_runner(self, store: object | None = None) -> object:
        """The determinism gate. Not optional: a runner that skips it fails the run that counts."""
        return fixture_runner_provider.harness_runner(store)


#: The object the entry point resolves to.
{symbol}_runner_provider = {symbol.title().replace("_", "")}RunnerProvider()
'''


class _RunnerScaffold:
    """`astro-mine plugin new runner <dir>` — a package registering a Bench execution backend."""

    name = "runner"
    help = "a Bench execution backend (astro_mine.bench.runners)"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.description = (
            "Scaffold a package that contributes an execution backend to Bench. The entry-point "
            "name is the --runner id, and it is folded into the scorecard's content hash."
        )
        parser.add_argument(
            "--runner",
            default="demo",
            help="the --runner id this backend registers as (default: demo)",
        )
        parser.add_argument("--distribution", help="distribution name (default: directory name)")
        parser.add_argument("--module", help="import package (default: distribution, `-` as `_`)")

    def run(self, args: argparse.Namespace) -> int:
        from astro_mine.bench.baseline._registry import _BUILTINS

        target = Path(args.output)
        distribution = args.distribution or target.name
        module = args.module or re.sub(r"[-.]", "_", distribution)
        runner = args.runner

        if runner in _BUILTINS:
            print(
                f"astro-mine plugin new runner: {runner!r} is a built-in runner id — a built-in "
                f"always wins resolution, so this plugin would install, register, and never be "
                f"reached. Pick your own id with --runner.",
                file=sys.stderr,
            )
            return _USAGE_ERROR
        if not re.fullmatch(r"[a-z0-9][a-z0-9_-]*", runner):
            print(
                f"astro-mine plugin new runner: {runner!r} is not a usable runner id; it is typed "
                f"after `--runner` on a command line. Pass --runner explicitly.",
                file=sys.stderr,
            )
            return _USAGE_ERROR
        if not module.isidentifier() or keyword.iskeyword(module):
            print(
                f"astro-mine plugin new runner: {module!r} is not a usable Python package name; "
                f"pass --module explicitly",
                file=sys.stderr,
            )
            return _USAGE_ERROR

        files = {
            target / "pyproject.toml": _pyproject(
                distribution=distribution, module=module, runner=runner
            ),
            target / "src" / module / "__init__.py": _module(runner=runner),
        }
        existing = [path for path in files if path.exists()]
        if existing and not args.force:
            listing = ", ".join(str(path) for path in existing)
            print(f"{listing}: file exists (use --force to overwrite)", file=sys.stderr)
            return 1
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
        print(
            f"\nInstall it and it is a first-class CLI option:\n  pip install -e {target}\n"
            f"  astro-mine-bench score --runner {runner}"
        )
        return 0


def _symbol(name: str) -> str:
    """A runner id may carry a hyphen; a Python symbol may not."""
    return re.sub(r"[-.]", "_", name)


runner_scaffold = _RunnerScaffold()
